site_name: Biologynote
nav:
    - Home: index.md
    - IG: 
        - 'Chapter 9 Transport in animals': ./IG/transport_in_animals.md
theme: material
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format